name: Delete Doc Comment

on:
  workflow_call:
    inputs:
      github_repo_id:
        required: true
        type: string
      pr_number:
        required: true
        type: string
    secrets:
      write_token:
        required: false

jobs:
  build_and_package:
    runs-on: ubuntu-latest

    steps:
      - name: Set env variables
        # This was copied from Hugging Face Doc Builder
        # TODO - we aren't using lysandre's token here hehe. just placeholder for now...going to manually pass token every time rn
        run: |
          if [ -z "${{ secrets.WRITE_TOKEN }}" ]
          then
            echo "Token not set, using Lysandre's"
            echo "write_token=$(echo 'ghp_'$(wget -qO- lysand.re/doc-build-dev)'bm')" >> $GITHUB_ENV
          else
            echo "Token was provided, using it..."
            echo "write_token=${{ secrets.WRITE_TOKEN }}" >> $GITHUB_ENV
          fi

      - name: Find pr comment
        if: ${{ always() }}
        uses: peter-evans/find-comment@v1
        id: find_comment
        with:
          issue-number: ${{ inputs.pr_number }}
          comment-author: nateraw

      - name: Update pr comment if necessary
        if: steps.find_comment.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          token: ${{ env.write_token }}
          edit-mode: replace
          body: |
            _The notebook links are not available anymore as the PR was closed or merged._