name: Make PR Comment

on:
  workflow_call:
    inputs:
      github_repo_id:
        required: true
        type: string
      pr_number:
        required: true
        type: string
      branch:
        required: true
        type: string
    secrets:
      write_token:
        required: false

jobs:
  make_colab_pr_comment:
    runs-on: ubuntu-latest

    steps:
      - name: Echo everything
        run: |
          echo "- github_repo_id: ${{ inputs.github_repo_id }}"
          echo "- pr_number: ${{ inputs.pr_number }}"
          echo "- branch: ${{ inputs.branch }}"
      - name: Checkout Action GitHub Repo
        uses: actions/checkout@v2
        with:
          repository: 'nateraw/colab-pr-action'
          path: cloned_action_repo

      - name: Checkout Source GitHub Repo
        uses: actions/checkout@v2
        with:
          repository: '${{ inputs.github_repo_id }}'
          # Relative path under $GITHUB_WORKSPACE to place the repository
          path: cloned_github_repo

      - name: Set env variables
        # This was copied from Hugging Face Doc Builder
        # TODO - we aren't using lysandre's token here hehe. just placeholder for now...going to manually pass token every time rn
        run: |
          if [ -z "${{ secrets.WRITE_TOKEN }}" ]
          then
            echo "Token not set, using Lysandre's"
            echo "write_token=$(echo 'ghp_'$(wget -qO- lysand.re/doc-build-dev)'bm')" >> $GITHUB_ENV
          else
            echo "Token was provided, using it..."
            echo "write_token=${{ secrets.WRITE_TOKEN }}" >> $GITHUB_ENV
          fi

      - name: Make comment
        shell: bash
        run: |
          cd cloned_action_repo
          git pull origin main
          pip install tabulate
          cd ..
          output=$(python cloned_action_repo/prepare_comment.py --root_dir cloned_github_repo --repo_id ${{ inputs.github_repo_id }} --branch ${{ inputs.branch }})
          echo "pr_comment_message=$output >> $GITHUB_ENV"

      - name: Find pr comment
        uses: peter-evans/find-comment@v1
        id: find_comment
        with:
          issue-number: ${{ inputs.pr_number }}
          comment-author: nateraw

      - name: Add pr comment if not present
        uses: thollander/actions-comment-pull-request@v1
        if: steps.find_comment.outputs.comment-id == ''

        with:
          message: ${{ env.pr_comment_message }}
          GITHUB_TOKEN: ${{ env.write_token }}

      - name: Update pr comment if necessary
        if: github.event.action == 'reopened' && steps.find_comment.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          token: ${{ env.write_token }}
          edit-mode: replace
          body: |
            ${{ env.pr_comment_message }}